{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"testFailed"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This can be useful to return early from a test if"},{"type":"text","text":" "},{"type":"text","text":"continuing after a failed assertion might be harmful."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The return value of this function is only meaningful"},{"type":"text","text":" "},{"type":"text","text":"if it is called from inside a test function."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/glib\/testfailed()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/GLib\/documentation\/GLib\/testFailed()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns whether a test has already failed. This will"},{"type":"text","text":" "},{"type":"text","text":"be the case when "},{"type":"codeVoice","code":"g_test_fail()"},{"type":"text","text":", "},{"type":"codeVoice","code":"g_test_incomplete()"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"codeVoice","code":"g_test_skip()"},{"type":"text","text":" have been called, but also if an"},{"type":"text","text":" "},{"type":"text","text":"assertion has failed."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"testFailed"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"testFailed()","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"s:4GLib10testFailedSbyF","modules":[{"name":"GLib"}]},"hierarchy":{"paths":[["doc:\/\/GLib\/documentation\/GLib"]]},"references":{"doc://GLib/documentation/GLib":{"role":"collection","title":"GLib","abstract":[],"identifier":"doc:\/\/GLib\/documentation\/GLib","kind":"symbol","type":"topic","url":"\/documentation\/glib"},"doc://GLib/documentation/GLib/testFailed()":{"role":"symbol","title":"testFailed()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"testFailed"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns whether a test has already failed. This will"},{"type":"text","text":" "},{"type":"text","text":"be the case when "},{"type":"codeVoice","code":"g_test_fail()"},{"type":"text","text":", "},{"type":"codeVoice","code":"g_test_incomplete()"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"codeVoice","code":"g_test_skip()"},{"type":"text","text":" have been called, but also if an"},{"type":"text","text":" "},{"type":"text","text":"assertion has failed."}],"identifier":"doc:\/\/GLib\/documentation\/GLib\/testFailed()","kind":"symbol","type":"topic","url":"\/documentation\/glib\/testfailed()"}}}