{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"testFail"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Do not use this function if the failure of a test could cause"},{"type":"text","text":" "},{"type":"text","text":"other tests to malfunction."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Calling this function will not stop the test from running, you"},{"type":"text","text":" "},{"type":"text","text":"need to return from the test function yourself. So you can"},{"type":"text","text":" "},{"type":"text","text":"produce additional diagnostic messages or even continue running"},{"type":"text","text":" "},{"type":"text","text":"the test."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If not called from inside a test, this function does nothing."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that unlike "},{"type":"codeVoice","code":"g_test_skip()"},{"type":"text","text":" and "},{"type":"codeVoice","code":"g_test_incomplete()"},{"type":"text","text":", this"},{"type":"text","text":" "},{"type":"text","text":"function does not log a message alongside the test failure."},{"type":"text","text":" "},{"type":"text","text":"If details of the test failure are available, either log them with"},{"type":"text","text":" "},{"type":"codeVoice","code":"g_test_message()"},{"type":"text","text":" before "},{"type":"codeVoice","code":"g_test_fail()"},{"type":"text","text":", or use "},{"type":"codeVoice","code":"g_test_fail_printf()"},{"type":"text","text":" "},{"type":"text","text":"instead."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/glib\/testfail()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/GLib\/documentation\/GLib\/testFail()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates that a test failed. This function can be called"},{"type":"text","text":" "},{"type":"text","text":"multiple times from the same test. You can use this function"},{"type":"text","text":" "},{"type":"text","text":"if your test failed in a recoverable way."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"testFail"},{"kind":"text","text":"()"}],"title":"testFail()","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"s:4GLib8testFailyyF","modules":[{"name":"GLib"}]},"hierarchy":{"paths":[["doc:\/\/GLib\/documentation\/GLib"]]},"references":{"doc://GLib/documentation/GLib/testFail()":{"role":"symbol","title":"testFail()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"testFail"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Indicates that a test failed. This function can be called"},{"type":"text","text":" "},{"type":"text","text":"multiple times from the same test. You can use this function"},{"type":"text","text":" "},{"type":"text","text":"if your test failed in a recoverable way."}],"identifier":"doc:\/\/GLib\/documentation\/GLib\/testFail()","kind":"symbol","type":"topic","url":"\/documentation\/glib\/testfail()"},"doc://GLib/documentation/GLib":{"role":"collection","title":"GLib","abstract":[],"identifier":"doc:\/\/GLib\/documentation\/GLib","kind":"symbol","type":"topic","url":"\/documentation\/glib"}}}